export const Texts = {
  adventure:
    "I am Hadi Masoumi. I was born in Iran country, Khozestan province , Iran country. I have been graduated from Azad university of Dezfoul in computer software engineering. ",
  skills:
"Html/CSS/JavaScript  - React.js - Node.js - Redux - React router - Design: figma",  experience:
    "my experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experiencemy experience",

  education:
    "my educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy educationmy education",
};
